### ISSUE TITLE
Serveur mail orthographe

### ISSUE THREAD

**Issue by Xerthes** [PeufOne/trocio#1]
Hello,

Dans le mail d'inscription à Trocio.ch le postmaster renvoi

_Bienvenue sur Trocio
<<Nom d'utilisateur>>, votre inscritpion c'est correctement déroulé..
Cliquer ici pour valider votre adresse mail._ 

Correction:
- inscription
- s'est
- un seul point à la fin

**Comment by PeufOne** [comment]
Merci,  
C'est corrigé. Ce sera effectif sur le site très prochainement.
